default: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  database: sb_development
  pool: 10
  reaping_frequency: 30
  username: stefunny
  password: 420

development: *default

test: *default

production:
  <<: *default
   adapter: postgresql
   host: localhost
   database: sb_production
   pool: 5
   username: stefunny
   password: 420
