default: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  database: sb_development
  pool: 10
  reaping_frequency: 30
  username: <%= ENV[username] %>
  password: <%= Rails.application.secrets[:database][:password] %>

development: *default

test: *default

production:
   adapter: postgresql
   host: localhost
   database: sb_production
   pool: 5
   username:
   password:
