development:
  adapter: postgresql
  encoding: UTF8
  host: localhost
  database: sb_development
  pool: 10
  reaping_frequency: 30
  username: stefunny
  password: 420

test:
  adapter: postgresql
  encoding: UTF8
  host: localhost
  database: sb_development
  pool: 10
  reaping_frequency: 30
  username: stefunny
  password: 420

production:
  url: <%=ENV['DATABASE_URL'] %>
  pool: <%= ENV['MAX_THREADS'] %>

